---
title: "Programa"
---

## DIA 1

+-------------+-----------------------------------------------------------+
| Horas       | Temas                                                     |
+=============+===========================================================+
| 08h30-09h00 | Receção e boas-vindas                                     |
+-------------+-----------------------------------------------------------+
| 09h00-12h30 | **Introdução ao R**                                       |
|             |                                                           |
|             | Iniciar um projeto em R                                   |
|             |                                                           |
|             | Boas práticas em programação                              |
|             |                                                           |
|             | Quarto \| Markdown                                        |
|             |                                                           |
|             | Tipos de Dados                                            |
|             |                                                           |
|             | Importar Dados                                            |
+-------------+-----------------------------------------------------------+
| 12h30-14h00 | Pausa Almoço                                              |
+-------------+-----------------------------------------------------------+
| 14h00-15h00 | **Manipulação de variáveis com Tidyverse**                |
|             |                                                           |
|             | Filtrar, selecionar, criar e renomear variáveis           |
+-------------+-----------------------------------------------------------+
| 15h00-15h15 | Coffee Break                                              |
+-------------+-----------------------------------------------------------+
| 16h30-17h30 | **Manipulação de variáveis com Tidyverse (continuação)**  |
|             |                                                           |
|             | Agrupar, sumarizar, e operações complexas                 |
+-------------+-----------------------------------------------------------+
| 17h30       | Fim do dia 1                                              |
+-------------+-----------------------------------------------------------+

## DIA 2

+---------------+----------------------------------------------------+
| Horas         | Temas                                              |
+===============+====================================================+
| 08h30-09h00   | Receção                                            |
+---------------+----------------------------------------------------+
| 09h00-12h30   | **Visualização de dados**                          |
|               |                                                    |
|               | Introdução ao ggplot2                              |
+---------------+----------------------------------------------------+
| 12h30-14h00   | Pausa Almoço                                       |
+---------------+----------------------------------------------------+
| 14h00-15h00   | **Visualização de dados (continuação)**            |
|               |                                                    |
|               | Time-series                                        |
|               |                                                    |
|               | Bar charts                                         |
|               |                                                    |
|               | Scaterplots                                        |
|               |                                                    |
|               | Mapas                                              |
|               |                                                    |
|               | **Tabelas e modelos**                              |
|               |                                                    |
|               | Tabelas estáticas e dinâmicas                      |
|               |                                                    |
|               | Regressão Linear                                   |
|               |                                                    |
|               | Regressão Logística                                |
|               |                                                    |
|               | Visualização de modelos                            |
+---------------+----------------------------------------------------+
| 15h00-15h15   | Coffee Break                                       |
+---------------+----------------------------------------------------+
| 16h30-17h30   | **Exercícios de visualização de dados**            |
+---------------+----------------------------------------------------+
| 17h30         | Fim do dia 2                                       |
+---------------+----------------------------------------------------+

## DIA 3

+---------------+----------------------------------------------------+
| Horas         | Temas                                              |
+===============+====================================================+
| 08h30-09h00   | Receção                                            |
+---------------+----------------------------------------------------+
| 09h00-12h30   | **Apoio com ChatGPT 4**                            |
|               |                                                    |
|               | Revisão de código                                  |
|               |                                                    |
|               | Documentação de código                             |
|               |                                                    |
|               | **Relatórios dinâmicos**                           |
|               |                                                    |
|               | Produção de documentos word, html e pdf em Quarto  |
|               |                                                    |
|               | Publicação de resultados no QuartoPubs             |
+---------------+----------------------------------------------------+
| 12h30-14h00   | Pausa Almoço                                       |
+---------------+----------------------------------------------------+
| 14h00-15h00   | **Dashboards**                                     |
|               |                                                    |
|               | Shiny App ou Flexdashboards                        |
|               |                                                    |
|               | **GitHub**                                         |
|               |                                                    |
|               | Integração GitHub com R                            |
|               |                                                    |
|               | Pull, Push, Commit                                 |
+---------------+----------------------------------------------------+
| 15h00-15h15   | Coffee Break                                       |
+---------------+----------------------------------------------------+
| 16h30-17h30   | **Avaliações**                                     |
+---------------+----------------------------------------------------+
| 17h30         | Fim do dia 3                                       |
+---------------+----------------------------------------------------+
